### ISSUE TITLE
[proposal] Remove bootstrap as bower dependency

### ISSUE THREAD

**Issue by infomiho** [itsjavi/bootstrap-colorpicker#153]
Are there any dependencies from Bootstrap other than this:

``` css
.dropdown-menu {
    position: absolute;
    top: 100%;
    left: 0;
    z-index: 1000;
    display: none;
    min-width: 160px;
    padding: 5px 0;
    margin: 2px 0 0;
    font-size: 14px;
    text-align: left;
    list-style: none;
    background-color: #fff;
    background-clip: padding-box;
    border: 1px solid #ccc;
    border: 1px solid rgba(0,0,0,.15);
    border-radius: 4px;
    box-shadow: 0 6px 12px rgba(0,0,0,.175);
}
```

I use it without Bootstrap (only added your CSS, your JS and the CSS I posted here) in a project and I think it's unnecessary to list bootstrap as dependency.
